name: Java CI with Gradle used Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eataku:latest .

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eataku:latest

  run-docker-image-on-ec2:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/eataku:latest

      - name: Docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      - name: Docker run new container
        run: sudo docker run --name eataku --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/eataku:latest

      - name: Delete Docker image
        run: sudo docker system prune -f
